name: Trigger Jenkins on Main Branch Only

on:
  push:
    branches:
      - main  # Only trigger Jenkins for main
jobs:
  trigger-jenkins:
    runs-on: windows-latest
    steps:
      - name: Trigger Jenkins Job
        shell: powershell
        run: Invoke-WebRequest -Uri "http://your-jenkins-url/job/your-job-name/build?token=your-token" -Method Post

